### ISSUE TITLE
as I run `/git follow git://github.com/opdenkamp/xbmc.git Eden-pvr Dharma`

### ISSUE THREAD

**Issue by anaderi** [errbotio/err-gitbot#12]
it fails:

```
 An error happened while processing a message ("/git follow git://github.com/yandex/rep.git"): Traceback (most recent call last):
  File "/Users/anaderi/miniconda/envs/aot-py3/lib/python3.5/site-packages/errbot/core.py", line 456, in _execute_and_send
    reply = method(mess, match) if match else method(mess, args)
  File "/Users/anaderi/git/AOT-errbot/data/plugins/errbotio/err-gitbot/gitBot.py", line 142, in git_follow
    installed_plugin_repos = self.get_installed_plugin_repos()
AttributeError: 'GitBot' object has no attribute 'get_installed_plugin_repos'
"
Traceback (most recent call last):
  File "/Users/anaderi/miniconda/envs/aot-py3/lib/python3.5/site-packages/errbot/core.py", line 456, in _execute_and_send
    reply = method(mess, match) if match else method(mess, args)
  File "/Users/anaderi/git/AOT-errbot/data/plugins/errbotio/err-gitbot/gitBot.py", line 142, in git_follow
    installed_plugin_repos = self.get_installed_plugin_repos()
AttributeError: 'GitBot' object has no attribute 'get_installed_plugin_repos'
```

**Comment by egon0** [comment]
should be fixed with #14
